### PR TITLE
Add cont, buf-conn, http2, pg, pg-types, racket-tcp, web-server-racket, web-server-racket-hello-world

### PR DESCRIPTION
**Pull request by ysangkok**
Added packages, starting with the leaves of the dependency tree:
<dl>
<dt><tt>cont</tt>
<dd>Double-barreled continuations. Used in the <tt>pg</tt>, <tt>http2</tt>, <tt>web-server-racket</tt> packages.
<dt><tt>buf-conn</tt>
<dd>Buffered connection (as in TCP). Based on continuations. Let's you only read the amount of bytes you want.
<dt><tt>pg-types</tt>
<dd>Data types for PostgreSQL clients. Used in the <tt>pg</tt> and <tt>http2</tt> packages.
<dt><tt>http2</tt>
<dd>Continuation based HTTP2 server. No IO. Used in <tt>web-server-racket</tt>.
<dt><tt>pg</tt>
<dd>Continuation based PostgreSQL client. No IO use. Used in <tt>web-server-racket</tt>.
<dt><tt>racket-tcp</tt>
<dd>Thin bindings to the <tt>racket/tcp</tt> library. Supports concurrency using the Racket custodian.
<dt><tt>web-server-racket</tt>
<dd>HTTP2 server with PostgreSQL access. See usage example in <tt>web-server-racket-hello-world</tt>. Only supports Racket due to reliance on the <tt>racket-tcp</tt> library.
<dt><tt>web-server-racket-hello-world</tt>
<dd>Example demo web server that computes 1+1 on a PostgreSQL server and returns the result over HTTP2. Racket only.
</dl>

### CODE REVIEW

**Comment by ysangkok** [comment]
Failure seems lsp related. I'll pull again once main passes CI

**Comment by stefan-hoeck** [comment]
I just started a re-run. Let's see if this works now.

**Comment by stefan-hoeck** [comment]
Could you please rebase this to be up to date with the current HEAD? We need the new split-up version of lsp from HEAD in order for the CI to succeed.

**Comment by ysangkok** [comment]
@stefan-hoeck I don't have access to a CLi right now and I don't think I can rebase using the web interface. But it should be possible to squash merge and achieve the same result.

**Comment by ysangkok** [comment]
@stefan-hoeck I have now rebased as requested!

**Comment by stefan-hoeck** [comment]
Thanks for these additions!

**Pull request merged**
