### PR TITLE
add spidr to db

### PR DESCRIPTION
**Pull request by joelberkeley**

### CODE REVIEW

**Comment by stefan-hoeck** [comment]
I know it's still WIP, but you might want to change the package's name from game-2048 to spidr. ;-)

**Comment by joelberkeley** [comment]
> I know it's still WIP, but you might want to change the package's name from game-2048 to spidr. ;-)

nah :p

**Comment by joelberkeley** [comment]
is there some way to check if this works? I want to get this right first time, to avoid rewriting git history

**Comment by joelberkeley** [comment]
is suppose i was expecting some kind of CI

**Comment by stefan-hoeck** [comment]
> i suppose i was expecting some kind of CI

You can add the following to a local `pack.toml` file and run (from the same directory or one of its child directories) `pack install spidr`:

```toml
[custom.all.spidr]
type   = "github"
url    = "https://github.com/joelberkeley/spidr"
commit = "pack"
ipkg   = "spidr.ipkg"
```

And yes, there should be some CI given that we have all the functionality already there for building the nightlies.

**Comment by stefan-hoeck** [comment]
Hmm, at least on my system I get some ambiguity errors (I'm on the latest nightly):

```sh
Error: While processing right hand side of deleteAt. Ambiguous elaboration. Possible
results:
    Util.List.deleteAt k xs
    Data.List.deleteAt k xs
```

**Comment by joelberkeley** [comment]
> Hmm, at least on my system I get some ambiguity errors (I'm on the latest nightly):
> 
> ```shell
> Error: While processing right hand side of deleteAt. Ambiguous elaboration. Possible
> results:
>     Util.List.deleteAt k xs
>     Data.List.deleteAt k xs
> ```

yes, "pack" branch is the same as "master" atm. I'm preparing to merge the necessary changes

**Comment by joelberkeley** [comment]
ready to merge

**Pull request merged**
