### PR TITLE
[ add ] adding idrisGL (https://github.com/ECburx/Idris2GL) to Pack

### PR DESCRIPTION
**Pull request by ECburx**
Thanks!

### CODE REVIEW

**Comment by ECburx** [comment]
Sorry to mention that the following libs are needed during CI.

```
libsdl1.2-dev
libsdl-image1.2-dev
libsdl-mixer1.2-dev
libsdl2-image-dev
libsdl2-ttf-dev
libsdl2-gfx-dev
libsdl2-mixer-dev
```

**Comment by ECburx** [comment]
OK, CI dependencies are added.

**Comment by ECburx** [comment]
Fixed some errors in the library repo. Could you re-run the checks?

**Comment by ECburx** [comment]
Seems not to be the problem of this library now.

```
[ info ] The following packages built successfully:
         ...
         - idrisGL (no tests run)
         ...
[ warning ] The following packages failed to build:
            - monad-bayes(failing dependencies: free)
            - prob-fx(failing dependencies: free)
[ warning ] The following packages could not be resolved:
            - free
            - fvect
[ fatal ] 4 packages failed to build.
```

**Comment by stefan-hoeck** [comment]
> Seems not to be the problem of this library now.
> 
> ```
> [ info ] The following packages built successfully:
>          ...
>          - idrisGL (no tests run)
>          ...
> [ warning ] The following packages failed to build:
>             - monad-bayes(failing dependencies: free)
>             - prob-fx(failing dependencies: free)
> [ warning ] The following packages could not be resolved:
>             - free
>             - fvect
> [ fatal ] 4 packages failed to build.
> ```

I'll rerun CI.

**Pull request merged**
