### PR TITLE
Add ncurses library to pack registry.

### PR DESCRIPTION
**Pull request by mattpolzin**
I've finally modified the NCurses build to run C helper compilation through `ipkg` hooks so it should now be a reasonable addition to the Pack package set.

### CODE REVIEW

**Comment by stefan-hoeck** [comment]
Do we need to install some additional Ubuntus libs during CI for this to build successfully?

**Comment by mattpolzin** [comment]
Oh, yeah. Sorry for that oversight!

I've got the following installed against ubuntu:latest via apt in the CI for ncurses-idris:
`libncurses-dev`, `libc6-dev`. 

I'd imagine that at some point you'd draw the line for "bloat" required to build a package? Let me know if you're ok with adding to the CI deps for this package.

**Comment by stefan-hoeck** [comment]
> Oh, yeah. Sorry for that oversight!
> 
> I've got the following installed against ubuntu:latest via apt in the CI for ncurses-idris: `libncurses-dev`, `libc6-dev`.
> 
> I'd imagine that at some point you'd draw the line for "bloat" required to build a package? Let me know if you're ok with adding to the CI deps for this package.

Feel free to go ahead and add them. Bloat is very manageable at the moment. :-)

**Comment by mattpolzin** [comment]
I wasn't totally sure if I needed to add the deps to the remaining workflow (I left it off for now). It seems to me like I would, but I noticed the remaining working doesn't have the build-time dependency for pg-idris installed so either it just happens to be on the CI image to begin with or else the last workflow doesn't need to build the packages.

**Comment by stefan-hoeck** [comment]
> I wasn't totally sure if I needed to add the deps to the remaining workflow (I left it off for now). It seems to me like I would, but I noticed the remaining workflow doesn't have the build-time dependency for pg-idris installed so either it just happens to be on the CI image to begin with or else the last workflow doesn't need to build the packages.

The remaining CI run is the one building the new nightly. It runs in `ubuntu-latest` unlike the others, which run in a docker container with pack preinstalled, therefore it comes with some of the dependencies already pre-installed. I'm actually planning to use the same procedure as in `ci-test` (which is only for manual testing) for `ci-db`, but I haven't found the time to make the change. You can leave `ci-db` as it is for now. Probably I manage to "fix" it later today.

**Comment by mattpolzin** [comment]
Huh. The CI failure right now is actually an Idris build failure. I’ll dig in. I know wheat the error is saying, I’m just surprised to see it since this same commit should have been built the last time CI ran for ncurses-idris.

**Pull request merged**
